version: '3.8'

services:
  parsely:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parsely
    stdin_open: true
    tty: true
    env_file:
      - .env
    volumes:
      - ./output:/app/output
      - ./parsed_history.json:/app/parsed_history.json
