version: '3.8'

services:
  parsely:
    build: .
    container_name: parsely
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - OUTPUT_ROOT_DIR=/app/data
    restart: unless-stopped
